# Generated by Django 3.1.2 on 2021-02-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_about_contact_main_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=255)),
                ('home_discription', models.CharField(max_length=455)),
            ],
        ),
    ]
