# Generated by Django 3.1.2 on 2021-02-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20210221_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_date',
            new_name='date_posted',
        ),
    ]
