# Generated by Django 3.1.2 on 2021-02-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20210221_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='summery',
            new_name='side_summery',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='writers_name',
            field=models.CharField(default='Admin', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='writers_summery',
            field=models.TextField(default='I hope this article was helpful to you, Thank you'),
        ),
    ]
