# Generated by Django 3.1.2 on 2021-03-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20210223_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
