# Generated by Django 3.1.2 on 2021-04-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_auto_20210405_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='gmail_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
