# Generated by Django 3.1.2 on 2021-09-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_auto_20210511_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
