# Generated by Django 3.1.2 on 2021-09-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply_Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Supply_Category',
            new_name='Categorys',
        ),
    ]
