# Generated by Django 3.1.2 on 2021-09-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_auto_20210920_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='category',
            new_name='categorys',
        ),
    ]
