# Generated by Django 3.1.2 on 2021-09-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_auto_20210921_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_supplies',
            old_name='supply_category',
            new_name='supply_categorys',
        ),
    ]
