# Generated by Django 3.1.2 on 2021-09-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0024_auto_20210921_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='Supply_Categorys',
        ),
    ]
