# Generated by Django 3.1.2 on 2021-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_auto_20210925_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
